#!/usr/bin/env python3
"""
Build the one font file the site serves.

Astro's font pipeline fetches Google's Bengali subset of Noto Sans Bengali and
ships it as-is. That file is a variable font whose weight axis runs 100 to 900,
and forty percent of its bytes are the interpolation data for that whole range.
The site only ever asks for 400 to 800, so the rest is paid for and never used.

This narrows the axis to 400..800 and drops glyph names, which are for authoring
tools and nothing else. Every weight the CSS uses still comes out of one file,
so nothing on screen changes. No codepoint is removed: the character set stays
exactly Google's Bengali subset, which matters because worlds can be added
through the admin panel and a glyph trimmed today would be a missing letter
tomorrow.

    python3 -m venv .venv && .venv/bin/pip install fonttools brotli
    .venv/bin/python scripts/make-font.py

It writes the woff2 into public/fonts/ under a name containing a hash of its
own bytes, so the year-long cache header is safe, and rewrites the two files
that need to know that name.
"""
import hashlib
import io
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'public', 'fonts')
CSS_OUT = os.path.join(ROOT, 'src', 'styles', 'font.css')
TS_OUT = os.path.join(ROOT, 'src', 'data', 'font.ts')

FAMILY = 'Noto Sans Bengali'
CSS_URL = 'https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400..800&display=swap'
# a browser UA, or Google hands back the old truetype format instead of woff2
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
WEIGHT_MIN, WEIGHT_MAX = 400, 800


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def main() -> int:
    try:
        from fontTools.ttLib import TTFont
        from fontTools.varLib import instancer
    except ImportError:
        print('needs fonttools and brotli: pip install fonttools brotli', file=sys.stderr)
        return 1

    css = fetch(CSS_URL).decode('utf-8')
    # the bengali block is the first @font-face Google returns; take its src and
    # its unicode-range together so the CSS we write matches the file we ship
    block = re.search(r'/\* bengali \*/(.*?)\}', css, re.S)
    if not block:
        print('could not find the bengali face in Google\'s CSS', file=sys.stderr)
        return 1
    src = re.search(r'url\((https://[^)]+\.woff2)\)', block.group(1)).group(1)
    urange = re.search(r'unicode-range:\s*([^;]+);', block.group(1)).group(1).strip()

    raw = fetch(src)
    font = TTFont(io.BytesIO(raw))
    before = len(raw)

    if 'fvar' not in font:
        print('expected a variable font; Google returned a static cut', file=sys.stderr)
        return 1

    font.flavor = None                       # decompress before editing
    buf = io.BytesIO(); font.save(buf); buf.seek(0)
    font = TTFont(buf)

    instancer.instantiateVariableFont(font, {'wght': (WEIGHT_MIN, WEIGHT_MAX)}, inplace=True)
    font['post'].formatType = 3.0            # glyph names are for font editors

    font.flavor = 'woff2'
    out = io.BytesIO(); font.save(out)
    data = out.getvalue()
    digest = hashlib.sha256(data).hexdigest()[:10]
    name = f'noto-sans-bengali-{WEIGHT_MIN}-{WEIGHT_MAX}.{digest}.woff2'

    os.makedirs(OUT_DIR, exist_ok=True)
    for old in os.listdir(OUT_DIR):
        if old.startswith('noto-sans-bengali-') and old != name:
            os.remove(os.path.join(OUT_DIR, old))
    with open(os.path.join(OUT_DIR, name), 'wb') as f:
        f.write(data)

    with open(CSS_OUT, 'w', encoding='utf-8') as f:
        f.write(
            '/* Generated by scripts/make-font.py. Do not edit by hand.\n'
            f'   {FAMILY}, Google\'s Bengali subset, weight axis narrowed to '
            f'{WEIGHT_MIN}..{WEIGHT_MAX}. One file serves every weight the site uses. */\n'
            '@font-face {\n'
            f'  font-family: "{FAMILY}";\n'
            '  font-style: normal;\n'
            f'  font-weight: {WEIGHT_MIN} {WEIGHT_MAX};\n'
            '  font-display: swap;\n'
            f'  src: url("/fonts/{name}") format("woff2");\n'
            f'  unicode-range: {urange};\n'
            '}\n'
        )

    with open(TS_OUT, 'w', encoding='utf-8') as f:
        f.write(
            '/** Generated by scripts/make-font.py. The hashed name of the one font\n'
            ' *  file the site serves, so the layout can preload it by its real URL. */\n'
            f"export const FONT_URL = '/fonts/{name}';\n"
        )

    print(f'{before} -> {len(data)} bytes  ({100 - len(data) * 100 // before}% smaller)')
    print(f'wrote public/fonts/{name}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
