/** Generated by scripts/make-font.py. The hashed name of the one font
 *  file the site serves, so the layout can preload it by its real URL. */
export const FONT_URL = '/fonts/noto-sans-bengali-400-800.95b2d88278.woff2';
